name: pulltemp-daily-task
on:
  schedule:
    - cron: '0 20 12 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests BeautifulSoup4
    - name: execute file
      run:
        python pulltemp.py
